// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_VariableName = {__proto__:null,fn:8, let:34, if:44, then:46, else:48}
export const parser = LRParser.deserialize({
  version: 14,
  states: "+dQVQPOOOOQO'#Cy'#CyQVQPOOOqQPO'#CcO!SQPO'#CjOOQO'#D['#D[OOQO'#C}'#C}O!ZQPO'#CuO#RQPO'#DZOOQO'#DY'#DYOOQO'#DU'#DUQlQPOOO#mQPO'#C^O#rQPO'#CoO#wQPO'#CqO$YQPO'#ClOOQO-E6w-E6wO$_QPO'#DVO$|QPO,58}O%UQPO,59cO%ZQPO,59UOOQO,59U,59UO%bQPO,59UO#wQPO'#CwOOQO-E6{-E6{O%mQPO'#DOO%{QPO,59uQVQPO'#DPQlQPOOO&gQPO,58xO#wQPO,59ZO&lQPO,59]O&qQQO,59WO&vQPO'#CdOOQO,59q,59qO'OQPO'#CzO'TQPO1G.iOOQO1G.i1G.iOOQO1G.}1G.}OOQO1G.p1G.pO']QPO1G.pOOQO'#C|'#C|O'hQPO1G.pO']QPO1G.pOOQO,59j,59jOOQO-E6|-E6|OOQO,59k,59kOOQO-E6}-E6}O'OQPO'#CcO'{QPO1G.dOOQO1G.u1G.uO#wQPO1G.wO#wQPO1G.rOOQO'#DX'#DXO&vQPO'#DXO(QQQO'#DWOOQO,59O,59OO(]QPO'#DVOOQO,59f,59fOOQO-E6x-E6xOOQO7+$T7+$TO(hQPO7+$[O({QPO7+$[OOQO7+$[7+$[OOQO-E6z-E6zOOQO,59g,59gOOQO-E6y-E6yOOQO7+$O7+$OO)WQPO7+$cOOQO7+$^7+$^O)]QPO,59sO&vQPO,59rOOQO<<Gv<<GvO)bQPO<<GvP)uQPO'#C|O#wQPO<<G}OOQO1G/_1G/_OOQO1G/^1G/^OOQOAN=bAN=bOOQOAN=iAN=i",
  stateData: "*]~OvOS~ORTOS[OURO]SOa_Of^OjTOwPO~ORaOURO]SOf^OjTO~O[eO~PVORTOUgO]SOjTOliXtiXwiXTiX[iX_iXgiXhiX~OliOt}Xw}XT}X[}X_}Xg}Xh}X~ORmO~OdnO~ORTOURO]SOf^OjTO~ORpO~OXqOR!OXTyXT!OXU!OXZyX]!OXj!OXl!OX~OTuOZsO~OTvO~O[wO~PVO[wO_yOwyO~ORTOUgO]SOjTO~OliOt}aw}aT}a[}a_}ag}ah}a~OU!QO~Og!TO~Ob!UO~OR!VOU!WO~OR!ZO~OT!^OZsO~O[!aO_yOwyO~OS[O[!aO_yOa_OwyO~P#wO]SO~OY!iOTzXZzX~OXqOTyXZyX~OS[O[!jO_yOa_OwyO~P#wO[!jO_yOwyO~Oh!mO~OT!nO~OS[O[!pO_yOa_OwyO~P#wOS[O_yOa_OwyO~P#wOdYjRj~",
  goto: "(_!PPP!QPPPP!]!rPPPPP!vP!QPP#_P#_PPP#qP$WP$l${%R%]%m&T&ZPPPP&a&t&{'U'Z#_'ycYOQSdkz!_!k!lp]OQRS^dgknz!T!U!_!k!l!mR!RmTra!ZtTOQRSV^dgiknz!T!U!_!k!l!mR!e!RqXOQRS^dgknz!T!U!_!k!l!mpWOQRS^dgknz!T!U!_!k!l!mR|iuTOQRSV^dgiknz!T!U!_!k!l!mQQOU`QdkQdSTkZlQtbR!]tQ{fQ!`xT!d{!`QzfS!_x{W!bz!_!k!lR!k!`rVOQRS^dgiknz!T!U!_!k!l!mRhVQjWR}jQlZR!PlSZOQQfSQxdQ!OkX!cz!_!k!lSbR!QR![sQ!YqQ!h!WR!o!iV!Xq!W!ibYOQSdkz!_!k!lScRgQo^Q!SnQ!f!TQ!g!UR!q!muUOQRSV^dgiknz!T!U!_!k!l!m",
  nodeNames: "⚠ Program FnDef VariableName fn ) ( ParamList TypeAnnot : -> , } { Block ; LetDef let = LambdaExpr => IfExpr if then else Application Number ParenExpr Operator",
  maxTerm: 46,
  nodeProps: [
    ["openedBy", 5,"(",12,"{"],
    ["closedBy", 6,")",13,"}"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: "$m~RbXY!ZYZ!i]^!Zpq!Zxy!nyz!s{|!x|}!}}!O#S!Q![#a![!]#i!]!^#n!_!`#s!c!}$Q#R#S$Q#T#o$Q#o#p$c#q#r$h~!`Rv~XY!Z]^!Zpq!Z~!nOw~~!sOU~~!xOT~P!}OlP~#SOZ~R#XPlP!`!a#[Q#aOYQ~#fPj~!Q![#a~#nOX~~#sO_~R#xPbQ!`!a#{P$QOdP~$VSR~!Q![$Q!c!}$Q#R#S$Q#T#o$Q~$hO]~~$mO[~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value) => spec_VariableName[value] || -1}],
  tokenPrec: 421
})
